# Generated by Django 4.2.4 on 2024-02-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stationapi', '0002_refund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='username',
            new_name='user',
        ),
    ]
