# Generated by Django 4.2.4 on 2024-02-25 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stationapi', '0004_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='refund',
            name='amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stationapi.payment'),
        ),
    ]
