# Generated by Django 4.2.4 on 2024-02-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stationapi', '0005_remove_refund_created_at_remove_refund_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='amount_ac',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='train',
            name='amount_nonac',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='train',
            name='amount_sleeper',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='train',
            name='type',
            field=models.CharField(choices=[('Non AC', 'Non AC'), ('AC', 'AC'), ('Sleeper', 'Sleeper')], default='AC', max_length=200),
        ),
    ]
