# Generated by Django 4.2.4 on 2024-02-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stationapi', '0006_train_amount_ac_train_amount_nonac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='type',
        ),
    ]
