# Generated by Django 4.2.4 on 2024-02-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stationapi', '0012_remove_booking_is_confirmed_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reserved_seats',
            field=models.IntegerField(),
        ),
    ]
