# Generated by Django 4.2.4 on 2024-03-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stationapi', '0014_payment_booking_alter_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
    ]
