# Generated by Django 4.2.4 on 2024-03-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stationapi', '0016_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_no',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='seat_capacity',
            field=models.PositiveIntegerField(default=70),
        ),
    ]
