# Generated by Django 4.2.4 on 2024-03-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stationapi', '0017_booking_seat_no_train_seat_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat_no',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
