# Generated by Django 4.2.4 on 2024-03-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stationapi', '0018_alter_booking_seat_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
