# Generated by Django 4.2.4 on 2024-03-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stationapi', '0019_alter_refund_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seat_no',
        ),
    ]
