# Generated by Django 4.2.4 on 2024-03-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stationapi', '0021_remove_train_seat_capacity_traincapacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traincapacity',
            name='user',
        ),
    ]
