# Generated by Django 4.2.4 on 2024-03-14 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stationapi', '0022_remove_traincapacity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traincapacity',
            name='train',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Stationapi.train'),
        ),
    ]
