# Generated by Django 4.2.4 on 2024-03-15 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stationapi', '0025_alter_traincapacity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traincapacity',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stationapi.train'),
        ),
    ]
