# Generated by Django 4.2.4 on 2024-03-18 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stationapi', '0026_alter_traincapacity_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stationapi.station'),
        ),
        migrations.AlterField(
            model_name='traincapacity',
            name='type',
            field=models.CharField(choices=[('Non AC', 'Non AC'), ('AC', 'AC'), ('Sleep er', 'Sleeper')], max_length=100),
        ),
    ]
